### ISSUE TITLE
Add 'ttyecho'

### ISSUE THREAD

**Issue by osospeed** [ArchStrike/ArchStrike#168]
https://aur.archlinux.org/packages/ttyecho-git/

**Comment by xorond** [comment]
Hello, I am seeing you are the owner of the package. Is it possible to add in a license?

**Comment by osospeed** [comment]
The idea is from : [http://www.humbug.in/2010/utility-to-send-commands-or-data-to-other-terminals-ttypts/]()
I informed him. Waiting for a reply from him ... any license suggestion ?

I find it very useful, e.g. chaining commands (but with different terminals).
Do you know an alternative ?
