### ISSUE TITLE
Request: xrop

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#173]
https://github.com/acama/xrop

**Comment by archey** [comment]
@acama It was requested that we add this to our repo, however I notice its missing proper licensing. We can pull from the tag releases, but would it be possible to license and tag the libxdisasm as well.

**Comment by acama** [comment]
I will try to take care of it over the weekend.

**Comment by archey** [comment]
@acama thanks, we will revisit this pkg
