### ISSUE TITLE
Request: Triton

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#174]
https://github.com/JonathanSalwan/Triton.git

**Comment by archey** [comment]
This is busted in boost 1.60, waiting for an update to 1.61 to fix a compilation error with multiprecision and gcc 6.1

compilation errors

/usr/include/boost/multiprecision/cpp_int.hpp:193:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));

https://github.com/boostorg/multiprecision/commit/f9c8f9ec091ad232c0a291904f7839d665d098e0

**Comment by vdun** [comment]
@JonathanSalwan

**Comment by archey** [comment]
@vdun this is an issue upstream that wont be fixed until the new boost 1.61 is released. As soon as its in Arch we will revisit this package

**Comment by archey** [comment]
Waiting on response from this issue https://github.com/JonathanSalwan/Triton/issues/484
