### ISSUE TITLE
Request: biteye

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#190]
https://github.com/BatchDrake/biteye

**Comment by xorond** [comment]
This package has no license and is poorly documented, I don't think it qualifies. Closing this issue.

**Comment by vdun** [comment]
@BatchDrake

**Comment by BatchDrake** [comment]
Hey, I didn't know there were still people interested in this. Anyways, biteye is sloppy, limited and deprecated. You would probably find Vix more useful: it lets you open several files at the same time and has other neat features like Hilbert views and multiple window interface. 

I'm a bit tight on time these days but if you give me a list of requirements on documentation I could work on it some other time, and ping you when it's done.

Regarding the licensing, it's GPLv3. I can specify it more formally somewhere if you want.

Thanks for you interest, btw!
