### ISSUE TITLE
Request: binglide

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#191]
https://github.com/wapiflapi/binglide

**Comment by Cthulu201** [comment]
The dev recommends this now:
https://github.com/wapiflapi/veles
Close this and open a new one for ^^?

**Comment by vdun** [comment]
veles is already on blackarch.
There is also an AUR: https://aur.archlinux.org/packages/veles-bin/

Besides that, it is always good to have alternatives ;)

**Comment by xorond** [comment]
We don't care about what blackarch has, we're a different project. If you want the pkg added you should submit a pkgbuild or open a new issue for it.
