### ISSUE TITLE
Request: box-js

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#194]
https://github.com/CapacitorSet/box-js

**Comment by xorond** [comment]
I don't see a license on this package. Closing until it has one.

**Comment by vdun** [comment]
@CapacitorSet

**Comment by CapacitorSet** [comment]
@vdun, thank you for the ping (and for submitting my project!).

@xorond, I just added MIT licensing.

**Comment by xorond** [comment]
Done!
