### ISSUE TITLE
The bully package missing signature.

### ISSUE THREAD

**Issue by drathir** [ArchStrike/ArchStrike#2]
Loks like https://github.com/ArchStrike/ArchStrike/tree/master/archstrike-testing/bully on installation attempt show:

error: bully: missing required signature
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

builidlog: http://archstrike.org:81/in-log/bully-1.0.22-2-x86_64.log.html

**Comment by archey** [comment]
This has been corrected, pkg is signed and updated please try again

**Comment by drathir** [comment]
Confirm, now workin corectly...

**Comment by drathir** [comment]
Thanks a lot all looks fine now... Greetings...
