### ISSUE TITLE
Request: hashtopus

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#209]
https://github.com/curlyboi/hashtopus

**Comment by xorond** [comment]
I appreciate you trying, but it would be easier on us if you came up with an example PKGBUILD for the requested packages.

**Comment by vdun** [comment]
I put them here as a TODO list for the community (including me).
Thanks for you continuous efforts!

**Comment by archey** [comment]
Closing because you are commiting help to blackarch but not us

**Comment by vdun** [comment]
I'm contributing to Archlinux.
Closing kills ArchStrike!
