### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by ahtss** [ArchStrike/ArchStrike#233]
DEBUG - Gen Initramfs
DEBUG - arch-chroot /mnt mkinitcpio -p linux
INFO - ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
INFO -   -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
INFO - ==> Starting build: 4.7.6-1-ARCH
INFO -   -> Running build hook: [base]
INFO -   -> Running build hook: [udev]
INFO -   -> Running build hook: [autodetect]
INFO -   -> Running build hook: [modconf]
INFO -   -> Running build hook: [block]
INFO -   -> Running build hook: [filesystems]
INFO -   -> Running build hook: [keyboard]
INFO -   -> Running build hook: [fsck]
ERROR - ==> ERROR: file not found: `fsck.btrfs'
ERROR - ==> WARNING: No fsck helpers found. fsck will not be run on boot.
INFO - ==> Generating module dependencies
INFO - ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux.img
ERROR - ==> WARNING: errors were encountered during the build. The image may not be complete.
INFO - ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
INFO -   -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
INFO - ==> Starting build: 4.7.6-1-ARCH
INFO -   -> Running build hook: [base]
INFO -   -> Running build hook: [udev]
INFO -   -> Running build hook: [modconf]
INFO -   -> Running build hook: [block]
ERROR - ==> WARNING: Possibly missing firmware for module: wd719x
ERROR - ==> WARNING: Possibly missing firmware for module: aic94xx
INFO -   -> Running build hook: [filesystems]
INFO -   -> Running build hook: [keyboard]
INFO -   -> Running build hook: [fsck]
INFO - ==> Generating module dependencies
INFO - ==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-fallback.img
INFO - ==> Image generation successful
ERROR - arch-chroot /mnt mkinitcpio -p linux

**Comment by archey** [comment]
Moving this to the correct, repository thanks for bringing it to our attention.
