### ISSUE TITLE
Add MobSF

### ISSUE THREAD

**Issue by iMuzaffar** [ArchStrike/ArchStrike#260]
Links:
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF
http://jd.benow.ca/

and add some more mobile application pentesting tools

thanks

**Comment by archey** [comment]
Thanks for adding the issue and links to them, the MobSf will be interesting due to the django requirement but its doable. 

We already have jd-gui, however it is out of date we will push an update to it asap.

**Comment by xorond** [comment]
Updated jd-gui https://github.com/ArchStrike/ArchStrike/commit/1b68d85c9980ab6b78ba2f3236f7c344f1b05cac
