### ISSUE TITLE
w3af GUI wrong version of xdot

### ISSUE THREAD

**Issue by andrewzeneski** [ArchStrike/ArchStrike#270]
I was able to get the w3af GUI working by installing version 0.4 of xdot removing 0.7.2 that is installed from pacman. It appears to me that xdot 0.7.2 is for Python3 / GTK3; version 0.6 appears to be the last python2 version. I choose 0.4 as that is what is installed by default on ubuntu 12.04 which is the OS/version used in the "official" docker image.

My "fix" was to override the installed xdot:

`$ sudo /usr/bin/pip2 install xdot==0.4`

**Comment by andrewzeneski** [comment]
Just to followup 0.6 seems to work perfectly fine as well.

**Comment by archey** [comment]
@andrewzeneski thanks for the bug report, let me see what I can do to fix it. I'll let you know in a few

**Comment by archey** [comment]
@andrewzeneski to fix this we have pushed an update to our python2-xdot pkg to drop it back to 0.6, it will be version locked and we will build the py3 version if needed. Thanks for the report, it should build soon.

**Comment by andrewzeneski** [comment]
Looks good @archey -- GUI seems to be working now 👍

**Comment by archey** [comment]
@andrewzeneski no problem I will close this ticket, feel free to let us know if you see anymore issues
