### ISSUE TITLE
cisco-torch not recognizing Net::SSH::Perl

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#284]
When launching cisco-torch the following error is produced: [error] Net::SSH::Perl perl module is not installed 

Currently running on archlinux 4.9.8-1 x86_64 with perl 5.24.1 and perl-net-ssh-perl (2.01-3)

**Comment by strayArch** [comment]
Made a PR w/ the fix, it's a missing dependency `perl-crypt-x`. PR #340

**Comment by xorond** [comment]
fixed on https://github.com/ArchStrike/ArchStrike/commit/1b73c8dcbff03a448b96c61892e5d9c6e04dda1e
