### ISSUE TITLE
mfterm fails to load shared library

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#287]
Currently running on archlinux 4.9.8-1 x86_64
core/readline 7.0.003-1 and multilib/lib32-readline 7.0-1 are isntalled
```
mfterm: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```

**Comment by archey** [comment]
Pushed rebuild for new readline in community, tested locally on box is working as it should.

**Comment by Wh1t3Fox** [comment]
Tested after rebuild. Now working
