### ISSUE TITLE
affcat fails to load shared library

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#292]
Currently running on archlinux 4.9.8-1 x86_64
core/readline 7.0.003-1 and multilib/lib32-readline 7.0-1 are isntalled
```
affcat: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

```

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/a4bdcbfc8347d7587ea726a6c3db1d821fdf429a

It should be fixed now

**Comment by Wh1t3Fox** [comment]
Tested and working
