### ISSUE TITLE
Add pkgs to archstrike-meta

### ISSUE THREAD

**Issue by Wh1t3Fox** [ArchStrike/ArchStrike#302]
swaks
p0f
afl-utils
lynis
nikto
cadaver
grabber
httrack
zaproxy
sqlitebrowser
findmyhash
hydra
words
medusa
ncrack
cowpatty
freeradius
freeradius-client
blueranger
hackrf
gnuradio-companion
gqrx
clang
tcpflow
sslsplit
sslstrip
miredo
ptunnel
dcfldd
extundelete
foremost
binwalk
gtk-recordmydesktop
recordmydesktop
truecrypt
cherrytree
thc-ipv6

**Comment by Wh1t3Fox** [comment]
added thc-ipv6 to list

**Comment by archey** [comment]
Added pkgs to archstrike-meta and rebuilt it
