### ISSUE TITLE
Request: gpp-decrypt

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#321]
https://github.com/SecurityToolsArchive/gpp-decrypt

**Comment by archey** [comment]
This needs alot of patching and itd, be really nice if someone would add a license to it. The last time I tested this it wont even work in kali

**Comment by Cthulu201** [comment]
Project no longer exists on GitHub. Closing.

**Comment by vdun** [comment]
Alternative `GPPDecryption`: https://github.com/ArchStrike/ArchStrike/issues/354
