### ISSUE TITLE
Error updating/installing archstrike on Odroid-C2 manjaro-arm

### ISSUE THREAD

**Issue by rumlyne** [ArchStrike/ArchStrike#336]
I tried to add the archstrike repositories as in point 1 of the installation guide (https://archstrike.org/wiki/arm/armv8/odroid-c2) but after adding the 2 lines in /etc/pacman.conf and running pacman -Syy as sudo and root I received the following error messages after it completed updating core, extra and community but apparently failed to do so with archstrike:

error: failed retrieving file 'archstrike.db' from mirror.archstrike.org : SSL certificate problem: certificate is not yet valid
error: failed to update archstrike (download library error)

Restarting did not help and internet comnection works. Kernel version is 3.14.79-14-MANJARO-ARM

**Comment by xorond** [comment]
Hello. Can you please check your system time? (running `date` should work)

**Comment by rumlyne** [comment]
Hi!
You were right, the date and time were false. After installing and enabling ntpd I was now able to complete the rest of part 2 step 1 and am now getting a new error when I try to install the archstrike-mirrorlist package (step 3).
pacman completes checking keys in keyring and package integrity and then
```
error: archstrike-mirrorlist: missing required signature
error: failed to commit transaction (package missing required signature)
Errors occured, no packages were upgraded.
```

**Comment by xorond** [comment]
Hi, there shouldn't be a problem with the mirrorlist package AFAIK. Can you please provide a full log?

**Comment by xorond** [comment]
@rumlyne any update? I'll close the issue in a few days..

**Comment by rumlyne** [comment]
@xorond No, I'm sorry I don't have time to work at it atm. Please close it. Thank you for your help!
