### ISSUE TITLE
PGP key error during install in Virtualbox

### ISSUE THREAD

**Issue by lawrencedark** [ArchStrike/ArchStrike#339]
ArchStrike-openbox-2016.07.21-x86_64.iso
Host machine: Arch Linux

Virtualbox 5.1.18 r114002

/tmp/archstrike-installer.log(snipped):
...
INFO - downloading libusb-1.0.21-1-x86_64.pkg.tar.xz...
INFO - downloading usbutils-008-1-x86_64.pkg.tar.xz...
INFO - downloading vi-1:070224-2-x86_64.pkg.tar.xz...
INFO - downloading which-2.21-2-x86_64.pkg.tar.xz...
INFO - downloading xfsprogs-4.10.0-1-x86_64.pkg.tar.xz...
INFO - downloading sudo-1.8.19.p2-1-x86_64.pkg.tar.xz...
INFO - checking keyring...
INFO - checking package integrity...
INFO - :: File /mnt/var/cache/pacman/pkg/krb5-1.13.7-1-x86_64.pkg.tar.xz is cor$
ERROR - error: krb5: signature from "Levente Polyak (anthraxx) <levente@levente$
INFO - Do you want to delete it? [Y/n]
ERROR - error: libpsl: signature from "Levente Polyak (anthraxx) <levente@leven$
INFO - :: File /mnt/var/cache/pacman/pkg/libpsl-0.17.0-1-x86_64.pkg.tar.xz is c$
ERROR - error: failed to commit transaction (invalid or corrupted package)
INFO - Do you want to delete it? [Y/n]
INFO - Errors occurred, no packages were upgraded.
ERROR - ==> ERROR: Failed to install packages to new root
ERROR - ^[[91mpacstrap /mnt base sudo^[[0m

**Comment by xorond** [comment]
Hello. Can you try running:
```
sudo pacman-key --refresh-keys
```

If that doesn't solve your problem, some issue might have happened during the download of the packages. In that case, please run:
```
sudo pacman -Scc # this will clean the pacman cache
sudo pacman -Syyu
```

**Comment by lawrencedark** [comment]
Will try that when I get home, thank you!

**Comment by xorond** [comment]
This was a previously known bug which has been fixed in the latest version of `archstrike-installer`. Can you run `pacman -Syy archstrike-installer` to update to the latest version and try again?

**Comment by xorond** [comment]
@lawrencedark update?

**Comment by lawrencedark** [comment]
Sorry, have been busy with work projects. Feel free to close the issue and if necessary I'll open a new one. Thanks!
