### ISSUE TITLE
cpublaster causes kernel panic on boot

### ISSUE THREAD

**Issue by karlguy** [ArchStrike/ArchStrike#345]
aparrently this package replaces the /usr/lib64 symlink to /usr/lib with a directory, which horribly breaks the boot process. cpublaster.so needs to be moved to /usr/lib.

**Comment by xorond** [comment]
Thank you for the heads up. I'm investigating.

**Comment by xorond** [comment]
I fixed the issue by patching the source here: https://github.com/ArchStrike/ArchStrike/commit/2a1d0166493cf1be92c98d7aaed99a3e25f01f50

It's getting built and it will be available in the repository really soon. Please let me know whether issue is solved or not.

**Comment by xorond** [comment]
I believe the issue is fixed. There have been reports of solved problems in the IRC channel. Feel free to reopen the issue if it comes up again.

**Comment by karlguy** [comment]
Works, thanks!
