### ISSUE TITLE
add missing dependencies to changeme

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#356]
https://github.com/ArchStrike/ArchStrike/commit/d1abe84748840a46103035148bdb9c7e27e31012

**Comment by xorond** [comment]
[ ] pyyaml
[ ] logutils
[ ] netaddr
[ ] requests
[ ] responses
[ ] nose
[ ] lxml
[ ] cerberus
[ ] shodan
[ ] python-libnmap
[ ] jinja2
[ ] paramiko
[ ] tabulate
[ ] sqlalchemy
[ ] psycopg2
[ ] pyodbc

**Comment by Cthulu201** [comment]
cerberus
jinja2
logutils
lxml
netaddr
nose
paramiko
persist-queue==0.3.1
psycopg2
pymongo
pyodbc
pysnmp
python-libnmap
python-memcached
pyyaml
redis
requests
selenium
shodan
sqlalchemy
tabulate

Note: some require repo added pkgs, like persist-queue
