### ISSUE TITLE
bettercap and ruby-colorize conflict

### ISSUE THREAD

**Issue by parosterbergmedina** [ArchStrike/ArchStrike#358]
Get an error from bettercap when doing a full install, see error message below. A `sudo pacman -S bettercap --force` solves the issue but I belive the 'colorize-0.8.1' directory should be removed from bettercap.
                                                                                                           
`error: failed to commit transaction (conflicting files)
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/CHANGELOG exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/LICENSE exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/README.md exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/Rakefile exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/colorize.gemspec exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/lib/colorize.rb exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/lib/colorize/class_methods.rb exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/lib/colorize/instance_methods.rb exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/lib/colorized_string.rb exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/gems/colorize-0.8.1/test/test_colorize.rb exists in both 'ruby-colorize' and 'bettercap'
/usr/lib/ruby/gems/2.4.0/specifications/colorize-0.8.1.gemspec exists in both 'ruby-colorize' and 'bettercap'
Errors occurred, no packages were upgraded.`

**Comment by xorond** [comment]
thanks, we're aware of this issue. this conflict is easy to fix, however there are other issues with it that need to be resolved to get it into a working state. therefore `bettercap` has been moved into `archstrike-testing` to resolve issue in d1abe84748840a46103035148bdb9c7e27e31012 and the upstream conflict issues such as this one.

also, you should **never** use `--force` unless explicit approval of its usage has been announced by us. we're not resposible of whatever happens to your system when you use `--force` to install a package.

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/f3f6d59022e25086268ae8f4cc5f00ea19eb73c9

This fixes the conflict, however `bettercap` is still not in working condition. I'm going to open another issue for that.
