### ISSUE TITLE
Add a wireless-regdb without any restrictions for pentesters

### ISSUE THREAD

**Issue by FrederikLauber** [ArchStrike/ArchStrike#370]
Hello,

it would be very nice if we could get a wireless-regdb package without any regional limits so you can play around with different frequencies or powers without fiddling around with the firmware of your wlan stick or building and signing your own.

Thanks in advance!

**Comment by Cthulu201** [comment]
I know there's one in core/wireless-regdb, and there are ways to mod the db (for example: https://blog.binaryfactory.ca/2012/09/setting-txpower-as-high-as-your-card-can-go/). To create the db.txt you would: regdbdump /usr/lib/crda/regulatory.bin > db.txt
2 big concerns I see are a lot of chips have limits burned into them, and if we created a pkg replacing the one upstream then we could be liable if it fries something. Thoughts?

**Comment by xorond** [comment]
closing this until further notice (if the idea comes up again in an applicable manner)
