### ISSUE TITLE
Request: Update ssldump source

### ISSUE THREAD

**Issue by mattweidner** [ArchStrike/ArchStrike#376]
Would it be possible to update the PKGBUILD to use a github source instead of the source on sourceforge? The [current PKGBUILD](https://archstrike.org/packages/ssldump) uses code taken from [https://sourceforge.net/projects/ssldump/files/](https://sourceforge.net/projects/ssldump/files/). Although this is where the project originated, it has not been actively developed since 2004. A source from github at [https://github.com/adulau/ssldump](https://github.com/adulau/ssldump) shows a recent bug fix in May. The github version also supports many more cipher suites than the sourceforge version. As a result, it can decrypt traffic that the sourceforge version cannot.

**Comment by xorond** [comment]
Hello. Thanks for the info. I'll be looking into this very soon.

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/36e12854db406883f31979acd3e0efeb22db904e
