### ISSUE TITLE
python2-miasm-git package is broken

### ISSUE THREAD

**Issue by m101** [ArchStrike/ArchStrike#378]
This package is broken as the proper elfesteem is not installed and depended upon.

The proper elfesteem to use : https://github.com/serpilliere/elfesteem.

**Comment by xorond** [comment]
Hi, thanks for the heads up. I'll let you know when it's solved.

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/b8db17a3c3b926218eeb31a367842d9b62ebdb0f

Should be fixed now, it will build soon. Please let me know if any other issue comes up.
