### ISSUE TITLE
ArchStrike OVA improper certificate configuration 

### ISSUE THREAD

**Issue by CathyDaddle** [ArchStrike/ArchStrike#379]
ArchStrike OVA cannot be downloaded due to improper certificate configuration on its website.
The website can be visited at https://uk.mirror.archstrike.org/ArchStrike.ova  OR https://archstrike.org/news/10016
Can someone suggest if the website has being moved to a new domain (URL).
Thanks for your answers in advance.

**Comment by xorond** [comment]
Hello. Thanks for informing us. Our UK mirror has been removed a while ago and it looks like we forgot to update the link on the website. I'll get to it as soon as I can.

**Comment by CathyDaddle** [comment]
Ok, thanks

**Comment by Cthulu201** [comment]
Mirror pulled; no long resolves.
