### ISSUE TITLE
hasher-git depends on non-existent python2-py-bcrypt

### ISSUE THREAD

**Issue by zack-emmert** [ArchStrike/ArchStrike#390]
The package `hasher-git` depends on `python2-py-bcrypt`, which doesn't exist. It should probably be replaced with `python2-bcrypt`.

**Comment by Cthulu201** [comment]
Thanks for the heads up. python2-py-bcrypt looks like it hasn't been updated in years. python2-bcrypt, as of v3.0.0, uses OpenBSD code. Package has been updated.
