### ISSUE TITLE
Fix dependency backdoor-factory-git for mitmf-git

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#395]
Moved mitmf-git to archstrike-testing as it depends on backdoor-factory-git which was removed a short while ago.
Need to fix mitmf-git as the pkg doesn't seem to work without this dep.

**Comment by comrumino** [comment]
Should be fixed for x86_64. See 9e80dbd9417f45b9e38da6e0caf3bc4f704b803f

**Comment by comrumino** [comment]
Closing since the dependency this issue is resolved. More testing would be wise.
