### ISSUE TITLE
updating angr to 7.7.12.16

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#401]
first, these dependencies must be updated:

- [x] 'python2-capstone'
- [x] 'python2-cachetools'
- [x] 'python2-networkx'
- [x] 'python2-rpyc'
- [x] 'python2-futures'
- [x] 'python2-progressbar'
- [x] 'python2-mulpyplexer'
- [x] 'python2-cooldict'
- [x] 'python2-ana' 
- [x] 'python2-archinfo'
- [x] 'python2-pyvex'
- [x] 'python2-claripy'
- [x] 'python2-simuvex'
- [x] 'python2-cle'
- [x] 'python2-pyelftools'
- [x] 'python2-cffi'
- [x] 'python2-bintrees'
- [x] 'python2-dpkt'

**Comment by comrumino** [comment]
Mostly done, claripy needs to be review for whether or not custom or z3-solver should be the dependency. Left both for now, because it works.

**Comment by comrumino** [comment]
Should be done. Feel free to do a more in depth testing @xorond . minimally the import should work.
