### ISSUE TITLE
updating eyewitness-git

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#410]
package needs new dependencies per setup.sh to work properly

**Comment by Cthulu201** [comment]
That's the ruby version. This is the main one:
https://github.com/FortyNorthSecurity/EyeWitness

**Comment by Cthulu201** [comment]
python2-pytesseract has been added to the repo as the needed dep.

**Comment by xorond** [comment]
will take a look at changing with the python version soon

**Comment by xorond** [comment]
currently having building problems with this, because of python2-pyqt4 dependency

**Comment by Cthulu201** [comment]
2 new alternative pkgs.
