### ISSUE TITLE
problem updating snort to 2.9.11.1

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#412]
```
checking for daq_load_modules in -ldaq_static... no

   ERROR!  daq_static library not found, go get it from
   http://www.snort.org/.
```
tried with `archstrike/libdaq-static` added as dependency, same error occurs.

**Comment by comrumino** [comment]
done

**Comment by AnDaLinShui** [comment]
checking for eth_set in -ldnet... yes
checking for eth_set in -ldumbnet... no
checking for dlsym in -ldl... yes
checking for daq_load_modules in -ldaq_static... no

   ERROR!  daq_static library not found, go get it from
   http://www.snort.org/.

how  to  done  this ?

**Comment by Cthulu201** [comment]
Hi,

Thanks for the email. Please make sure that daq-modules-config is in
your path when you configure snort.
https://seclists.org/snort/2015/q4/210
