### ISSUE TITLE
Unresolvable dependencies for a number of packages

### ISSUE THREAD

**Issue by Phoenix750** [ArchStrike/ArchStrike#415]
After following the setup instructions for installing archstrike on top of my existing arch linux system and trying to install a number of packages, I get an error that some packages could not be installed because they lack a dependency. A paste of the exact messages can be found [here](https://pastebin.com/B3mJTF22).

Thanks in advance.

**Comment by nemanjan00** [comment]
Can you give us your /etc/pacman.conf? Did you do pacman -Syy first?

**Comment by nemanjan00** [comment]
After taking a look at deps, it seams like those are all in AUR. Are you
using AUR client?

**Comment by Cthulu201** [comment]
Hi,

Thanks for letting us know. We'll update those packages as soon as we can.

**Comment by Phoenix750** [comment]
I ran -Syy first and [here](https://pastebin.com/PAUuaFy7) is a paste of my pacman.conf. I just tried to do it with yay, but that gave the same issue.

**Comment by Phoenix750** [comment]
I noticed that I only miss two more dependencies now: "python2-slowaes" and "webkitgtk". I don't know because there is being worked on the issue or because of something else, but I thought I'd let you know.

**Comment by Cthulu201** [comment]
Thanks for letting us know. Most were in Arch repositories, until they 
recently moved them out to AUR. So, we created our own deps to alleviate 
this issue in the future.

**Comment by Cthulu201** [comment]
Should be good now.
pacman -Syy
Then try again. Thanks.

**Comment by Cthulu201** [comment]
Upstream deps were removed. Created and updated deps for affected packages.

**Comment by Cthulu201** [comment]
```
Dep needed            pkg
------------------------------------------------
xmpppy                brut3k1t-git
mingw-w64-gcc         ps1encode-git
```

**Comment by Cthulu201** [comment]
```
Dep needed            pkg
------------------------------------------------
xmpppy                brut3k1t-git
mingw-w64-gcc         ps1encode-git
```

**Comment by Cthulu201** [comment]
Issue resolved.
