### ISSUE TITLE
update nassl and sslyze

### ISSUE THREAD

**Issue by xorond** [ArchStrike/ArchStrike#421]
nassl -> 2.1.2
moved to python3, gives gcc error while build process, needs to be investigated

ssylze -> 2.0.6
requires newest version of nassl

**Comment by comrumino** [comment]
The gcc error is from the dependencies not build built. So when including `deps/` it does not resolve things and a compile time error happens

**Comment by comrumino** [comment]
Added some extra comments in the PKGBUILD for nassl. Tested build and import with success.
