### ISSUE TITLE
`python-jinja2` conflicts with Arch Linux's `python-jinja`

### ISSUE THREAD

**Issue by doronbehar** [ArchStrike/ArchStrike#422]
Official Arch Linux community repository provides `python-jinja` which obviously conflicts with `python-jinja2` from the Arch Strike repositories. Either `python-jinja2` needs to be removed or modified with `provides=('python-jinja')` to it's `PKGBUILD` so it won't be marked as required when installed as a dependency.

Thanks.

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/2f61d0131b9f79ebbc5863f64f8866f0b6c4229c
removed from repo, thanks

**Comment by doronbehar** [comment]
What about all packages that depend on `python-jinja2` and not `python-jinja`?

**Comment by xorond** [comment]
hi,
there were 2 pkgs depending on `python-jinja2` and i've updated the dependencies accordingly now. thanks for the heads up. feel free to reopen the issue if you notice anything else.

https://github.com/ArchStrike/ArchStrike/commit/39ff01ec6f161e277e209ff2812386829736ec6f
https://github.com/ArchStrike/ArchStrike/commit/defb03f3f576ee8cfc9c4c5f0a1f1d164ad5b34f
