### ISSUE TITLE
wifiphisher is missing dependencies

### ISSUE THREAD

**Issue by toufikbelouadah** [ArchStrike/ArchStrike#424]
on archlinux trying to run wifiphisher after grabin' it from your repos shows missing scapy module and roguehostapd while the first is missing and can be installed manually the second is already installed and yet wifiphisher cant seem to import it which confused me 
Please revise and test wiphifisher on archlinux and keep me updated 
thanks

**Comment by xorond** [comment]
hi, i'm taking a look

**Comment by xorond** [comment]
https://github.com/ArchStrike/ArchStrike/commit/dfb05b4707817fc7fe1ad75db28ab1533fe950b0
https://github.com/ArchStrike/ArchStrike/commit/fc666743f17b69f49d7bdbd6599778e791f84963

after local tests the problem looks to be fixed. you should update your system with `pacman -Syyu` to get the latest pushes.
thanks for the help, feel free to reopen this if the issue persists.
