### ISSUE TITLE
IP-Tracer [Tool Request]

### ISSUE THREAD

**Issue by Rajkumrdusad** [ArchStrike/ArchStrike#427]
IP-Tracer is used to trace an ip address information.
Tool Link : https://github.com/Rajkumrdusad/IP-Tracer
If this tool is ready to be on ArchStrike so please add this tool.

**Comment by xorond** [comment]
hi, i don't really see the appeal of this tool to be honest. all the
functionalities of it can be achieved without it and it doesn't really
bring anything interesting to the table. so unfortunately i will have to
decline the request. have a nice day.

Rajkumar Dusad <notifications@github.com> schrieb am Di., 13. Nov. 2018
14:13:

**Comment by Rajkumrdusad** [comment]
Yaa that's right.

**Comment by Rajkumrdusad** [comment]
in archstrike there are lots of tool but i did find any tool witch trace an ip and retrive the information of any ip so you can add this tool on archstrike.

**Comment by xorond** [comment]
i checked the code, it looks to be sending api requests to a website. you
can do that with curl also :) we don't need a separate tool to make api
requests to a specific website, but thnaks for the thought.

Rajkumar Dusad <notifications@github.com> schrieb am Di., 13. Nov. 2018
15:00:

**Comment by Rajkumrdusad** [comment]
Ok

**Comment by Safwanna** [comment]
Hi

**Comment by Rajkumrdusad** [comment]
Hii
