### ISSUE TITLE
Unresolvable dependency for empire

### ISSUE THREAD

**Issue by demivi** [ArchStrike/ArchStrike#432]
Commit [93fc8a1](https://github.com/ArchStrike/ArchStrike/commit/93fc8a1544f6dcb49c652749b249d88cdff7f3ab) removed the python2-pygraphviz package which now breaks dependencies for empire:
```
resolving dependencies...
warning: cannot resolve "python2-pygraphviz", a dependency of "python2-altgraph"
warning: cannot resolve "python2-altgraph", a dependency of "python2-macholib"
warning: cannot resolve "python2-macholib", a dependency of "empire"
:: The following package cannot be upgraded due to unresolvable dependencies:
      empire
```

This package was available on the official repository for some time but it has been removed on March 2nd for Python 2:
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/pygraphviz&id=2f87bf0d96691d36c63d37ee7983f981811536c2

**Comment by Cthulu201** [comment]
Thanks for the heads up. Since Arch removed the split pkg we will need to recreate for Python 2. Should have this resolved soon.

**Comment by demivi** [comment]
Thanks!

**Comment by Cthulu201** [comment]
Pkg is now in repo. Please -Scc and -Syy before installing again. If you use an alternate mirror then it might be some time before it syncs with that mirror - we don't control their sync frequency.
