### ISSUE TITLE
[Tool request] munin

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#439]
https://github.com/Neo23x0/munin

**Comment by Cthulu201** [comment]
Looking into this. Some requirements will need to be packaged, too. There might be a configparser issue that would need to be fixed too.

**Comment by Cthulu201** [comment]
Added it as munin-git - arch has a different type of munin pkg. I don't have any valid keys at the moment. Please test and let me know if you're having any issues.

**Comment by Cthulu201** [comment]
Added. Closing due to lack of feedback.
