### ISSUE TITLE
Package 'secure-delete' is broken

### ISSUE THREAD

**Issue by TheT3ngu** [ArchStrike/ArchStrike#442]
secure-delete 3.1-4, as it is available in the archstrike-repo, is broken. An update is available and for example available in the AUR: https://aur.archlinux.org/packages/secure-delete/
Works fine, but anytime I -Syyu Pacman downgrades the package to the version in the archstrike-repo, which is pain in the ass. Please update

**Comment by Cthulu201** [comment]
Updated, tested, and pushed.
