### ISSUE TITLE
Prebuild template for Qubes OS

### ISSUE THREAD

**Issue by hegnuzalto** [ArchStrike/ArchStrike#443]
There is any chance that team make prebuild template for install in Qubes OS R4?

**Comment by Torxed** [comment]
I think this is something directed towards the Qubes community, and not ArchStrike.
ArchStrike is more a mirror, or addon to Arch Linux. 

See this topic: https://www.qubes-os.org/doc/templates/archlinux/ for more details on how a normal maintanance release towards Qubes is handled. This isn't something Arch Linux directly supports, it's the Qubes community that does.

**Comment by Cthulu201** [comment]
Correct. The way Qubes is designed, this is for their community. We only support Arch Linux.
