### ISSUE TITLE
MAT can't be upgraded due to unresolvable dependencies

### ISSUE THREAD

**Issue by emilysnow2477** [ArchStrike/ArchStrike#444]
Expected behavior: able to upgrade like normal, MAT receives updates. 

Actual behavior: MAT throws an error in pacman because `mutagen` is no longer a package. I believe it's `python-mutagen` now, but I could be wrong. 

MAT2 is also available, albeit the fact that the dev stated it's in beta: https://0xacab.org/jvoisin/mat2

**Comment by Cthulu201** [comment]
Thanks for the info. You're right, there's python{2}-mutagen now. We have updated the pkg. Should be in visible in the repo soon.
