### ISSUE TITLE
[Tool request] pyrebox

### ISSUE THREAD

**Issue by vdun** [ArchStrike/ArchStrike#446]
https://github.com/Cisco-Talos/pyrebox

**Comment by Cthulu201** [comment]
It would be a Python 2 package. Even if we package it today, possibly in less than a month it won't work anymore. Definitely something we would consider though. If you find a Python 3 compliant variant just reopen this request. Thanks.

**Comment by vdun** [comment]
Current development (python3) is on : https://github.com/Cisco-Talos/pyrebox/tree/python3migration
