### ISSUE TITLE
aarch64 perl-crypt-random-seed and perl-bytes-random-secure missing signature

### ISSUE THREAD

**Issue by Fructose38** [ArchStrike/ArchStrike#504]
I was trying to install pulledpork-git on my RPi3, but got stuck by these 2 packages missing signatures:
error: perl-crypt-random-seed: missing required signature
error: perl-bytes-random-secure: missing required signature
Thanks,
Regards,

**Comment by Cthulu201** [comment]
Sorry about the too long delay. This should be resolved within the hour. Thanks for bringing to our attention.
