### ISSUE TITLE
Unable to startx with 2020.07.28 Openbox build

### ISSUE THREAD

**Issue by LouieTian0209** [ArchStrike/ArchStrike#510]
Already checked SHA256 and SHA512, exactly the same as indicated on official website.

When it's time to startx the system just spews:
`xauth: timeout in locking authority file /home/archstrike/.Xauthority`

Then the user is dropped to a shell prompt.

I have tried the previous build from 2019 and that one works fine, so I'm assuming the latest build not being able to get into a live session with Openbox is a bug.

**Comment by xorond** [comment]
hi, and sorry for the delay

we've decided to deprecate the openbox build in favor of a minimal build, which can be found on https://archstrike.org/downloads

this acts only as an installation medium to run the installer and get a working system, the iso can be used in a VM as installation media to create an archstrike VM as well. many configurations are possible within the installer.

we are still considering which desktop environment to pick for the "live" ISO, but this might take a while
