### ISSUE TITLE
Error at installing  ArchStrike keyring

### ISSUE THREAD

**Issue by psy-C0DE-path** [ArchStrike/ArchStrike#512]
`[root@alarmpi ~]# pacman-key --init
[root@alarmpi ~]# dirmngr < /dev/null
dirmngr[595.0]: permanently loaded certificates: 139
dirmngr[595.0]:     runtime cached certificates: 0
dirmngr[595.0]:            trusted certificates: 139 (138,0,0,1)
Home: /root/.gnupg
Config: [none]
OK Dirmngr 2.2.21 at your service
[root@alarmpi ~]# pacman-key -r 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.
[root@alarmpi ~]# pacman-key --lsign-key 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
  -> Locally signing key 9D5F1C051D146843CDA4858BDE64825E7CBC0D51...
==> ERROR: 9D5F1C051D146843CDA4858BDE64825E7CBC0D51 could not be locally signed.
[root@alarmpi ~]# pacman -S archstrike-keyring
resolving dependencies...
looking for conflicting packages...

Packages (1) archstrike-keyring-20200930-2

Total Download Size:   0.01 MiB
Total Installed Size:  0.01 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 archstrike-keyring-20200930-2-any                                                13.7 KiB  0.00   B/s 00:00 [################################################################] 100%
(1/1) checking keys in keyring                                                                               [################################################################] 100%
downloading required keys...
:: Import PGP key 698DB1CE0D47E88B, "Mike Henze <cthulu201@archstrike.org>"? [Y/n] Y
error: key "698DB1CE0D47E88B" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
[root@alarmpi ~]# pacman -S archstrike-mirrorlist
resolving dependencies...
looking for conflicting packages...

Packages (1) archstrike-mirrorlist-20200110-1

Total Download Size:   0.00 MiB
Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 archstrike-mirrorlist-20200110-1-any                                              2.5 KiB  0.00   B/s 00:00 [################################################################] 100%
(1/1) checking keys in keyring                                                                               [################################################################] 100%
downloading required keys...
:: Import PGP key 698DB1CE0D47E88B, "Mike Henze <cthulu201@archstrike.org>"? [Y/n] Y
error: key "698DB1CE0D47E88B" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
[root@alarmpi ~]# `

**Comment by Cthulu201** [comment]
The pgp.mit.edu server has been wonky lately. Recommend the following:

pacman-key --keyserver pool.sks-keyservers.net -r 
9D5F1C051D146843CDA4858BDE64825E7CBC0D51

**Comment by psy-C0DE-path** [comment]
thanks. pacman-key worked, but still i cant instal archstrike-keyring
`pacman -S archstrike-keyring
resolving dependencies...
looking for conflicting packages...

Packages (1) archstrike-keyring-20200930-2

Total Download Size:   0.01 MiB
Total Installed Size:  0.01 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 archstrike-keyring-20200930-2-any                                                13.7 KiB  0.00   B/s 00:00 [################################################################] 100%
(1/1) checking keys in keyring                                                                               [################################################################] 100%
(1/1) checking package integrity                                                                             [################################################################] 100%
error: archstrike-keyring: signature from "Mike Henze (ArchStrike Dev) (”Those Who Sacrifice Liberty For Security Deserve Neither.” - Benjamin Franklin) <cthulu201@archstrike.org>" is unknown trust
:: File /var/cache/pacman/pkg/archstrike-keyring-20200930-2-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.`

**Comment by psy-C0DE-path** [comment]
After that i nedeed to locally sign the key for archstrike-keyring
`pacman-key --lsign-key 698DB1CE0D47E88B`
