### ISSUE TITLE
[out of date] `python-libpcap` is out of date.

### ISSUE THREAD

**Issue by dreirund** [ArchStrike/ArchStrike#527]
[In your repository, `python-libpcap`](https://github.com/ArchStrike/ArchStrike/blob/master/archstrike/python-libpcap/PKGBUILD) is at version 0.4.0.

[Upstream git](https://github.com/caizhengxin/python-libpcap/tags) has 0.4.1, and [PyPI](https://pypi.org/project/libpcap/#history) has 1.11.0b7.

Regards!

**Comment by comrumino** [comment]
The upstream of `pip install python-libpcap` and `pip install libpcap` have two different repositories as their source. The repository that we rely on is b/c it is a dependency for [pcredz](https://github.com/lgandx/PCredz). So, the latest dependency version available is indeed [0.4.1](https://github.com/caizhengxin/python-libpcap/tags). 

I can see the confusion coming from two python dependencies with very similar names.
