### ISSUE TITLE
Unable to run ./bdf_proxy.py 

### ISSUE THREAD

**Issue by Arafat05nov** [ArchStrike/ArchStrike#528]
File "./bdf_proxy.py", line 34, in <module>
    from libmproxy import controller, proxy, platform
ImportError: No module named libmproxy

**Comment by Cthulu201** [comment]
backdoor factory was python2-based, and was removed from the repo with the rest of the python2 pkgs.

**Comment by Arafat05nov** [comment]
> backdoor factory was python2-based, and was removed from the repo with the rest of the python2 pkgs.

Is there a way to download now
