### ISSUE TITLE
python-mechanicalsoup: Re-package for python 3.11, and out of date.

### ISSUE THREAD

**Issue by dreirund** [ArchStrike/ArchStrike#529]
Dear "Archstrike" team,

At least one package in your repository is outdated:

You provide the package `python-mechanicalsoup` [1], version 1.0.0-1. But when I
build from the AUR, I get version 1.1.0-1.

Also, your package is still packaged for python3.9, but we are at 3.11 now, so it won't work:

`pacman -Ql python-mechanicalsoup`:  
```
[...]
/usr/lib/python3.9/site-packages/
[...]
```

Please update.

Regards!

[1] https://archstrike.org/packages/python-mechanicalsoup

**Comment by Cthulu201** [comment]
Thanks. The update has been pushed. Should see the update in the repos soon.
